apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "whatsapp.labels" . | nindent 4 }}
    {{- include "whatsapp.selectorLabels" (dict "name" "minio" "root" .) | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.minio.storage }}
