global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8081']
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8082']
  - job_name: 'chat-service'
    static_configs:
      - targets: ['chat-service:8083']
  - job_name: 'message-service'
    static_configs:
      - targets: ['message-service:8084']
  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:8085']
  - job_name: 'media-service'
    static_configs:
      - targets: ['media-service:8086']
  - job_name: 'websocket-service'
    static_configs:
      - targets: ['websocket-service:8087']
