apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "whatsapp.labels" . | nindent 4 }}
    {{- include "whatsapp.selectorLabels" (dict "name" "postgres" "root" .) | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: {{ .Values.postgres.port }}
      targetPort: postgres
      protocol: TCP
  selector:
    {{- include "whatsapp.selectorLabels" (dict "name" "postgres" "root" .) | nindent 4 }}
