apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "whatsapp.labels" . | nindent 4 }}
    {{- include "whatsapp.selectorLabels" (dict "name" "chat-service" "root" .) | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.services.chatService.httpPort }}
      targetPort: http
      protocol: TCP
    - name: grpc
      port: {{ .Values.services.chatService.grpcPort }}
      targetPort: grpc
      protocol: TCP
  selector:
    {{- include "whatsapp.selectorLabels" (dict "name" "chat-service" "root" .) | nindent 4 }}
