apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "whatsapp.labels" . | nindent 4 }}
    {{- include "whatsapp.selectorLabels" (dict "name" "notification-service" "root" .) | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.services.notificationService.httpPort }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "whatsapp.selectorLabels" (dict "name" "notification-service" "root" .) | nindent 4 }}
