apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "whatsapp.labels" . | nindent 4 }}
    {{- include "whatsapp.selectorLabels" (dict "name" "mongodb" "root" .) | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: mongodb
      port: {{ .Values.mongodb.port }}
      targetPort: mongodb
      protocol: TCP
  selector:
    {{- include "whatsapp.selectorLabels" (dict "name" "mongodb" "root" .) | nindent 4 }}
